# How to use GPU

In [19]:
import torch
import torch.nn as nn

## Convert to CUDA tensor: cuda()

In [7]:
x = torch.cuda.FloatTensor(2,2)
x

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')

In [8]:
x = torch.FloatTensor(2, 2)

x

tensor([[0., 0.],
        [0., 0.]])

In [9]:
x.cuda() # x의 값을 gpu로 보내준다.

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')

In [10]:
d = torch.device('cuda:0') # 디바이스 지정

In [11]:
x.cuda(device=d)

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')

In [12]:
x.device # cuda는 move 개념이 아니라 copy라서 그대로 cpu

device(type='cpu')

## Convert to CUDA tensor: to()

In [13]:
x.to(device=d)

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')

## Convert to CPU tensor from CUDA tensor

In [14]:
x = torch.cuda.FloatTensor(2, 2)

In [15]:
x = x.cpu()

In [16]:
d = torch.device('cpu')
x = x.to(d)

## Move model from CPU to GPU.

In [17]:
def print_params(model):
    for p in model.parameters():
        print(p)

In [20]:
linear = nn.Linear(2, 2)

print_params(linear)

Parameter containing:
tensor([[-0.2222,  0.1500],
        [ 0.0447, -0.3362]], requires_grad=True)
Parameter containing:
tensor([-0.3687, -0.4729], requires_grad=True)


In [21]:
linear = linear.cuda()

print_params(linear)

Parameter containing:
tensor([[-0.2222,  0.1500],
        [ 0.0447, -0.3362]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([-0.3687, -0.4729], device='cuda:0', requires_grad=True)


In [22]:
linear = linear.cpu()

print_params(linear)

Parameter containing:
tensor([[-0.2222,  0.1500],
        [ 0.0447, -0.3362]], requires_grad=True)
Parameter containing:
tensor([-0.3687, -0.4729], requires_grad=True)


In [23]:
d = torch.device('cuda:0')
linear = linear.to(d)

print_params(linear)

Parameter containing:
tensor([[-0.2222,  0.1500],
        [ 0.0447, -0.3362]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([-0.3687, -0.4729], device='cuda:0', requires_grad=True)


In [24]:
linear.device

ModuleAttributeError: 'Linear' object has no attribute 'device'

## Tricks

In [25]:
x = torch.cuda.FloatTensor(2, 2)

In [26]:
x.new(2, 2)

tensor([[-1.0842e-19,  1.6843e+00],
        [ 4.4658e-02,  3.3623e-01]], device='cuda:0')

In [27]:
torch.zeros_like(x)

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')

In [28]:
torch.ones_like(x)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')

In [29]:
list(linear.parameters())[0].new(2, 2)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')