# PyTorch Useful Methods

In [1]:
import torch

### expand: copy the given tensor and concat those at desired dimension.

In [2]:
x = torch.FloatTensor([[[1, 2]],
                       [[3, 4]]])
print(x.size())

torch.Size([2, 1, 2])


In [3]:
y = x.expand(*[2,3,2])
print(y)
print(y.size())

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


#### Implement expand with cat.

In [4]:
y = torch.cat([x,x,x], dim = 1)
print(y)
print(y.size())

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


### randperm: Random Permutation

In [5]:
x = torch.randperm(10)
print(x)
print(x.size())

tensor([0, 7, 6, 8, 3, 9, 1, 2, 4, 5])
torch.Size([10])


### argmax: Return index of maximum values

In [16]:
x = torch.randperm(3**3).reshape(3,3,-1)
print(x)
print(x.size())

tensor([[[11, 15, 20],
         [ 1, 14,  7],
         [16, 18, 22]],

        [[ 6, 23,  5],
         [10, 26,  2],
         [13, 19,  9]],

        [[12,  4,  0],
         [17,  3, 25],
         [21,  8, 24]]])
torch.Size([3, 3, 3])


In [17]:
y = x.argmax(dim = -1) # 각 dim에서 가장큰 값의 인덱스를 반환해준다.
print(y)
print(y.size())

tensor([[2, 1, 2],
        [1, 1, 1],
        [0, 2, 2]])
torch.Size([3, 3])


### topk: Return tuple of top-k values and indices.

In [18]:
values, indices = torch.topk(x, k = 1, dim = -1)
print(values.size())
print(indices.size())

torch.Size([3, 3, 1])
torch.Size([3, 3, 1])


In [19]:
values

tensor([[[20],
         [14],
         [22]],

        [[23],
         [26],
         [19]],

        [[12],
         [25],
         [24]]])

In [9]:
print(values)

tensor([[[26],
         [23],
         [21]],

        [[24],
         [19],
         [15]],

        [[25],
         [20],
         [14]]])


In [10]:
print(indices)

tensor([[[2],
         [1],
         [0]],

        [[2],
         [0],
         [2]],

        [[1],
         [0],
         [2]]])


Note that topk didn't reduce the dimension, even in $k=1$ case.

In [11]:
print(values.squeeze(-1))
print(indices.squeeze(-1))

tensor([[26, 23, 21],
        [24, 19, 15],
        [25, 20, 14]])
tensor([[2, 1, 0],
        [2, 0, 2],
        [1, 0, 2]])


In [20]:
values.squeeze(-1).size()

torch.Size([3, 3])

In [12]:
print(x.argmax(dim=-1) == indices.squeeze(-1))

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [13]:
_, indices = torch.topk(x, k = 2, dim = -1)
print(indices.size())

print(x.argmax(dim = -1) == indices[:,:,0])

torch.Size([3, 3, 2])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [15]:
indices[:,:,0]

tensor([[2, 1, 0],
        [2, 0, 2],
        [1, 0, 2]])

In [14]:
torch.topk(x, k = 2, dim = -1)

torch.return_types.topk(
values=tensor([[[26, 11],
         [23, 22],
         [21, 18]],

        [[24, 16],
         [19, 10],
         [15,  9]],

        [[25,  4],
         [20, 17],
         [14,  6]]]),
indices=tensor([[[2, 1],
         [1, 0],
         [0, 2]],

        [[2, 1],
         [0, 2],
         [2, 0]],

        [[1, 0],
         [0, 1],
         [2, 1]]]))

### Sort by using topk

In [16]:
target_dim = -1
values, indices = torch.topk(x, k = x.size(target_dim), largest = True)

print(values)

tensor([[[26, 16,  8],
         [21, 12,  0],
         [20, 17,  1]],

        [[25, 19, 10],
         [18, 13,  2],
         [23, 15,  4]],

        [[24, 11,  3],
         [14,  6,  5],
         [22,  9,  7]]])


### Topk by using sort

In [17]:
k = 1
values, indices = torch.sort(x, dim = -1, descending = True)
values, indices = values[:,:,:k], indices[:,:,:k]

print(values.squeeze(-1))
print(indices.squeeze(-1))

tensor([[26, 21, 20],
        [25, 18, 23],
        [24, 14, 22]])
tensor([[0, 0, 1],
        [1, 0, 0],
        [2, 0, 0]])


### masked_fill: fill the value if element of mask is True.

In [18]:
x = torch.FloatTensor([i for i in range(3**2)]).reshape(3, -1)

print(x)
print(x.size())

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
torch.Size([3, 3])


In [19]:
mask = x > 4

print(mask)

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])


In [20]:
y = x.masked_fill(mask, value=-1)

print(y)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])


In [21]:
y = x.masked_fill(mask, value=-1)

print(y)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])


### Ones and Zeros

In [22]:
print(torch.ones(2, 3))
print(torch.zeros(2, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [23]:
x = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6]])
print(x.size())

torch.Size([2, 3])


In [24]:
print(torch.ones_like(x)) # x의 특성을 똑같이 반영해서 만듬, 연산을 위해서 씀 같은 데이터 유형등등 맞추기 위해서.
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
