# Gradient Descent

In [1]:
import torch
import torch.nn.functional as F

In [2]:
target = torch.FloatTensor([[.1, .2, .3],
                            [.4, .5, .6],
                            [.7, .8, .9]])

In [3]:
x = torch.rand_like(target)
# This means the final scalar will be differentiate by x.
x.requires_grad = True
# You can get gradient of x, after differentiation.
x

tensor([[0.1734, 0.7527, 0.6142],
        [0.5823, 0.8822, 0.6854],
        [0.7639, 0.2124, 0.0032]], requires_grad=True)

In [4]:
loss = F.mse_loss(x, target)
loss

tensor(0.1944, grad_fn=<MseLossBackward>)

In [5]:
threshold = 1e-5
learning_rate = 1.
iter_cnt = 0

while loss > threshold:
    iter_cnt += 1
    loss.backward() # Calculate gradients.
    
    x = x - learning_rate*x.grad
    
    x.detach_() # 다음 x랑 연관 끊어준다.
    x.requires_grad_(True)
    
    loss = F.mse_loss(x, target)
    
    print('%d-th Loss: %.4e' % (iter_cnt,loss))
    print(x)

1-th Loss: 1.1761e-01
tensor([[0.1571, 0.6298, 0.5444],
        [0.5418, 0.7973, 0.6664],
        [0.7497, 0.3430, 0.2025]], requires_grad=True)
2-th Loss: 7.1147e-02
tensor([[0.1444, 0.5343, 0.4901],
        [0.5103, 0.7312, 0.6517],
        [0.7387, 0.4445, 0.3575]], requires_grad=True)
3-th Loss: 4.3040e-02
tensor([[0.1346, 0.4600, 0.4478],
        [0.4858, 0.6798, 0.6402],
        [0.7301, 0.5235, 0.4780]], requires_grad=True)
4-th Loss: 2.6036e-02
tensor([[0.1269, 0.4022, 0.4150],
        [0.4667, 0.6399, 0.6313],
        [0.7234, 0.5850, 0.5718]], requires_grad=True)
5-th Loss: 1.5750e-02
tensor([[0.1209, 0.3573, 0.3894],
        [0.4519, 0.6088, 0.6243],
        [0.7182, 0.6327, 0.6447]], requires_grad=True)
6-th Loss: 9.5280e-03
tensor([[0.1163, 0.3223, 0.3695],
        [0.4403, 0.5846, 0.6189],
        [0.7141, 0.6699, 0.7015]], requires_grad=True)
7-th Loss: 5.7639e-03
tensor([[0.1126, 0.2952, 0.3541],
        [0.4314, 0.5658, 0.6147],
        [0.7110, 0.6988, 0.7456]], requi